networks:
  boursenet:
    driver: bridge

services:
  db:
    image: timescale/timescaledb:latest-pg16
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - "5432:5432"
    networks:
      - boursenet
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=ricou
      - POSTGRES_PASSWORD=monmdp
    volumes:
      - /home/hicham/Bureau/big-gragas/bourse/timescaledb:/var/lib/postgresql/data/timescaledb

  analyzer:
    image: my_analyzer
    depends_on:
        - db
    networks:
      - boursenet
    volumes:
      - /home/hicham/Bureau/big-gragas/bourse/data:/home/bourse/data/

  dashboard:
    image: my_dashboard
    networks:
      - boursenet
    ports:
      - "8050:8050"
